name: Build and deploy keycloak/2fa-email-authenticator base image to ECR

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PUBLIC_REPO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLIC_REPO_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Parse git tag
        id: release
        run: |
          echo version=$(echo ${{ github.ref_name }} | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/keycloak/2fa-email-authenticator:latest
            ${{ steps.login-ecr.outputs.registry }}/keycloak/2fa-email-authenticator:${{ steps.release.outputs.version }}
